version: 1

before:
  hooks:
    - go mod tidy

builds:
  - id: gol
    binary: gol
    dir: cmd/gol
    ldflags: "-s -w -X main.revision={{.Tag}}-{{.ShortCommit}}-{{.CommitDate}}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

brews:
  - name: gol
    repository:
      owner: kulapard
      name: homebrew-tap
      branch: master
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/kulapard/gol/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: taras+goreleaserbot@drapalyuk.com
    commit_msg_template: "Brew formula update for `{{ .ProjectName }}` version `{{ .Tag }}`"
    folder: Formula
    homepage: "https://github.com/kulapard/gol"
    description: "Terminal version of Conway's Game of Life written in Go"
    license: "MIT"
    test: |
      system "#{bin}/gol --version"

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc

checksum:
  name_template: 'checksums.txt'
